if status is-interactive
    atuin init fish | source
end

# gcloud needs a python it can import from; only pin it if that build is here.
if test -x /opt/homebrew/bin/python3.14
    set -gx CLOUDSDK_PYTHON /opt/homebrew/bin/python3.14
end
starship init fish | source
fish_vi_key_bindings

set -gx PATH $PATH $HOME/go/bin
set -gx PATH $PATH $HOME/.cargo/bin 

alias cm=chezmoi
alias ls=eza
alias eng-report="uv run --with google-genai python ~/scripts/eng-report.py"

# Sources the fzf theme
source ~/.config/fzf/themes/catppuccin-fzf-mocha.fish


# Zoxide: `cd` jumps by keyword, `cdi` picks interactively. Generated by zoxide
# itself so it tracks fish releases (fish 4.8+ no longer ships functions/cd.fish
# on disk). Skipped until the Brewfile has installed zoxide.
if command -q zoxide
    zoxide init --cmd cd fish | source
end


function zk --description 'Kill process on port'
    if test (count $argv) -eq 0
        echo "Usage: zk <port>"
        return 1
    end

    set port $argv[1]
    set pids (lsof -ti:$port 2>/dev/null)

    if test -z "$pids"
        echo "No process running on port $port"
    else
        echo $pids | xargs kill -9
        echo "Killed process(es) on port $port"
    end
end
# fnm (Fast Node Manager)
if command -q fnm
    fnm env --use-on-cd | source
end


# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init2.fish 2>/dev/null || :

alias cdd "cd ~/didero"
